export const shoesData = [
  {
    product_model: "Nike Air Max 90",
    brand: "Nike",
    price: 649.99,
    description:
      "The legendary Nike Air Max 90 running shoes with visible Air Max cushioning.",
    featured: false,
    target_group: "men",
    categories: ["Running", "Casual"],
    images: [
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576730/products/nike_air_max_90_1_ph2eou.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576730/products/NIKEAIRMAX97_2_wxpsxy.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576730/products/nike_air_max_90_2_sxuc0q.webp",
    ],
    variants: [
      { size: 37, quantity: 5 },
      { size: 38, quantity: 1 },
      { size: 39, quantity: 0 },
      { size: 40, quantity: 10 },
      { size: 41, quantity: 15 },
      { size: 42, quantity: 12 },
      { size: 43, quantity: 8 },
      { size: 44, quantity: 5 },
      { size: 45, quantity: 0 },
    ],
  },
  {
    product_model: "Nike Air Force 1 '07",
    brand: "Nike",
    price: 499.99,
    description:
      "The classic Nike Air Force 1 '07 model with iconic comfort and style.",
    featured: false,
    target_group: "men",
    categories: ["Lifestyle", "Casual"],
    images: [
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576729/products/nike_air_force_1_07_1_muql78.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576729/products/nike_air_force_1_07_2_n1inr0.webp",
    ],
    variants: [
      { size: 37, quantity: 0 },
      { size: 38, quantity: 1 },
      { size: 39, quantity: 2 },
      { size: 40, quantity: 6 },
      { size: 41, quantity: 2 },
      { size: 42, quantity: 5 },
      { size: 43, quantity: 0 },
      { size: 44, quantity: 5 },
      { size: 45, quantity: 0 },
    ],
  },
  {
    product_model: "Nike Blazer Mid '77 Vintage",
    brand: "Nike",
    price: 429.99,
    description:
      "The Nike Blazer Mid '77 Vintage combines old-school looks with modern comfort.",
    featured: false,
    target_group: "men",
    categories: ["Lifestyle", "Casual"],
    images: [
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576729/products/BLAZERMID77VNTG_1_itsesc.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576729/products/BLAZERMID77VNTG_2_awkcce.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576729/products/BLAZERMID77VNTG_3_axoddt.webp",
    ],
    variants: [
      { size: 37, quantity: 5 },
      { size: 38, quantity: 1 },
      { size: 39, quantity: 1 },
      { size: 40, quantity: 2 },
      { size: 41, quantity: 0 },
      { size: 42, quantity: 0 },
      { size: 43, quantity: 8 },
      { size: 44, quantity: 5 },
      { size: 45, quantity: 0 },
    ],
  },
  {
    product_model: "Nike Air Zoom Pegasus 38",
    brand: "Nike",
    price: 549.99,
    description:
      "The Nike Air Zoom Pegasus 38 is a versatile running shoe with Zoom Air cushioning.",
    featured: false,
    target_group: "men",
    categories: ["Running", "Performance"],
    images: [
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576732/products/WPEGASUSEASYONOLY_1_qow5fv.webp",
    ],
    variants: [
      { size: 37, quantity: 1 },
      { size: 38, quantity: 1 },
      { size: 39, quantity: 0 },
      { size: 40, quantity: 10 },
      { size: 41, quantity: 15 },
      { size: 42, quantity: 12 },
      { size: 43, quantity: 8 },
      { size: 44, quantity: 5 },
      { size: 45, quantity: 0 },
    ],
  },
  {
    product_model: "Nike InfinityRN 4 GORE-TEX",
    brand: "Nike",
    price: 629.99,
    description:
      "The Nike InfinityRN 4 GORE-TEX provides exceptional cushioning and support.",
    featured: false,
    target_group: "men",
    categories: ["Running", "Performance"],
    images: [
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576731/products/NIKEREACTXINFINITYRN4GTX_i1tnbr.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576731/products/NIKEREACTXINFINITYRN4GTX_2_jeyagd.webp",
    ],
    variants: [
      { size: 37, quantity: 5 },
      { size: 38, quantity: 1 },
      { size: 39, quantity: 0 },
      { size: 40, quantity: 10 },
      { size: 41, quantity: 2 },
      { size: 42, quantity: 3 },
      { size: 43, quantity: 0 },
      { size: 44, quantity: 0 },
      { size: 45, quantity: 0 },
    ],
  },
  {
    product_model: "Nike Air Max 97",
    brand: "Nike",
    price: 749.99,
    description:
      "The Nike Air Max 97 features a unique design and full-length Air Max cushioning.",
    featured: true,
    target_group: "men",
    categories: ["Lifestyle", "Casual"],
    images: [
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576730/products/NIKEAIRMAX97_egn4cc.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576730/products/NIKEAIRMAX97_2_wxpsxy.webp",
    ],
    variants: [
      { size: 37, quantity: 5 },
      { size: 38, quantity: 1 },
      { size: 39, quantity: 0 },
      { size: 40, quantity: 5 },
      { size: 41, quantity: 13 },
      { size: 42, quantity: 12 },
      { size: 43, quantity: 8 },
      { size: 44, quantity: 5 },
      { size: 45, quantity: 0 },
    ],
  },
  {
    product_model: "Nike Dunk Low",
    brand: "Nike",
    price: 529.99,
    description:
      "The Nike Dunk Low is a classic skate shoe with excellent cushioning.",
    featured: true,
    target_group: "men",
    categories: ["Skateboarding", "Lifestyle"],
    images: [
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576730/products/NIKEDUNKLOWNN_hxbbl4.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576730/products/NIKEDUNKLOWNN_2_pigajb.webp",
    ],
    variants: [
      { size: 37, quantity: 5 },
      { size: 38, quantity: 1 },
      { size: 39, quantity: 3 },
      { size: 40, quantity: 10 },
      { size: 41, quantity: 1 },
      { size: 42, quantity: 12 },
      { size: 43, quantity: 8 },
      { size: 44, quantity: 5 },
      { size: 45, quantity: 0 },
    ],
  },
  {
    product_model: "Nike Air VaporMax 2023 Flyknit",
    brand: "Nike",
    price: 899.99,
    description:
      "Nike Air VaporMax 2023 Flyknit combines modern design with incredible comfort.",
    featured: false,
    target_group: "men",
    categories: ["Running", "Lifestyle"],
    images: [
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576729/products/AIRVAPORMAX2023FK_loqgyx.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576729/products/AIRVAPORMAX2023FK_2_tifr2m.webp",
      "https://res.cloudinary.com/dtu0ehxly/image/upload/v1724576729/products/AIRVAPORMAX2023FK_3_mbzklq.webp",
    ],
    variants: [
      { size: 37, quantity: 5 },
      { size: 38, quantity: 1 },
      { size: 39, quantity: 6 },
      { size: 40, quantity: 10 },
      { size: 41, quantity: 2 },
      { size: 42, quantity: 12 },
      { size: 43, quantity: 8 },
      { size: 44, quantity: 5 },
      { size: 45, quantity: 10 },
    ],
  },
];
